### ISSUE TITLE
Reuse the Woocommerce EU VAT tax_id if exists

### ISSUE THREAD

**Issue by AnderPijoan** [quaderno/quaderno-woocommerce#8]
Hi,

We are testing Quaderno in order to add it to our company processes. We have a woocommerce site for B2B selling across Europe. Since it is B2B sales, we need to verify the customers EU VAT ID and we are using the Woocommerce EU VAT plugin.

The EU VAT plugin adds an extra input to the checkout form for cutomers to entner and validate their VAT tax id:

`<input type="text" class="input-text " name="billing_eu_vat_number" id="billing_eu_vat_number" placeholder="IVA Intracomunitario" value="">
`
Yesterday I installed the Quaderno woocommerce plugin and it adds another NIF or NIF-IVA input for the same purpose to the checkout form. 

`<input type="text" class="input-text " name="tax_id" id="tax_id" placeholder="NIF o NIF-IVA" value="" autocomplete="nope">
`
I've noticed that the plugin allows setting this field to optional but not hiding from the form (since we already have that info in the EU VAT plugin).

- Would it be possible that Quaderno Woocommerce plugin reuses the EU VAT "billing_eu_vat_number" if said plugin is installed instead of needting to create another input ("tax_id")?

Otherwise, could there be an intermediate solution for not having two inputs for the same data in the checkout form?

Thanks in advance and really looking forward to use Quaderno in our business.

**Comment by AnderPijoan** [comment]
![image](https://user-images.githubusercontent.com/1140190/101135527-37497300-360c-11eb-8604-3d06e0c3c311.png)

**Comment by polimorfico** [comment]
Hi Ander! Our plugin already collects and validates EU VAT numbers. 
Unfortunately we don't support extensions developed by thirds-parties.

**Comment by AnderPijoan** [comment]
So, the way to go is deactivating the EU VAT plugin and manage VAT numbers from your plugin right?

**Comment by polimorfico** [comment]
Correct.
