### ISSUE TITLE
Problem with free product

### ISSUE THREAD

**Issue by odoremieux** [quaderno/quaderno-woocommerce#9]
When trying to have a free product on Woocommerce, that doesn't require that many infos, just a name & an email. We can't checkout, Quaderno through some errors about billing_country, billing_state, billing_postcode, billing_city.
Is there some way to NOT use quaderno for some products with Woocommerce?

**Comment by polimorfico** [comment]
Unfortunately it's not possible to use Quaderno only with a subset of products. Sorry. We'll consider your suggestion for a future release.

**Comment by odoremieux** [comment]
At least it would be nice to have a way to not use Quaderno for some product, especially when the Tax Status is set to 'None'
